#数据库
#spring.datasource.url=jdbc:mysql://192.168.0.234:3306/moveinsp?useUnicode=true&characterEncoding=utf8
spring:
  #数据库
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    max-maxWait: 100
    min-idle: 8
    initial-size: 10
  #返回html
  thymeleaf:
    prefix: classpath:/WEB-INF/view/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  #静态文件路径
  mvc:
    static-path-pattern: /static/**

  #热部署
  devtools:
    restart:
      additional-paths: src/main/java
      exclude: static/**,public/**

  #日期数据格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

## Mybatis
#mybatis.typeAliasesPackage=com.google.ssm.domain
#mybatis.mapperLocations=classpath:mapper/*.xml
#mybatis.configuration.mapUnderscoreToCamelCase=true
mybatis:
  configuration:
   cache-enabled: false


#logging:
#  level.com.google.ssm: debug
logging:
  level.root: info
  level.com.google.ssm: debug
  path: logs/
  file: log.log
  
#mapper
mapper:
  mappers: com.google.ssm.util.MyMapper
  not-empty: false
  identity: MYSQL

###################  MyBatis 分页插件配置  ###################
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

server:
  port: 8081


