
server:
  port: 8060


logging:
  level:
    com.github.dge1992: debug

spring:
  datasource:
    url: jdbc:mysql://192.168.0.135:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: 123456
    filters: log4j,wall,mergeStat


#mybatis:
#  type-aliases-package: com.github.dge1992.ssm.domain
#  mapper-locations: classpath:mappers/*.xml
#  configuration:
#    cache-enabled: false
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

mybatis-plus:
  mapper-locations:  classpath:mappers/*.xml
  typeAliasesPackage: com.github.dge1992.ssm.domain
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true
